using System.Security.Principal;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FoodDeliveryApplication
{
    /// <summary>
    /// Get the details of items in list
    /// </summary>
    public class ItemDetails
    {
        /// <summary>
        /// static item field
        /// </summary>
        private static int s_itemID = 100;
        /// <summary>
        /// ItemID property Autogenerated
        /// </summary>
        /// <value></value>
        public string ItemID { get; }
        /// <summary>
        /// OrderID for ordered item
        /// </summary>
        /// <value></value>
        public string OrderID { get; set; }
        /// <summary>
        /// FoodID information of ordered food id
        /// </summary>
        /// <value></value>
        public string FoodID { get; set; }
        /// <summary>
        /// Count for ordered food
        /// </summary>
        /// <value></value>
        public int PurchaseCount { get; set; }
        /// <summary>
        /// Total amount of order food
        /// </summary>
        /// <value></value>
        public double PriceOfOrder { get; set; }

        /// <summary>
        /// parameterized constructor used for assigning the values to itemDetails
        /// </summary>
        /// <param name="orderID"></param>
        /// <param name="foodID"></param>
        /// <param name="purchaseCount"></param>
        /// <param name="priceOfOrder"></param>

        public ItemDetails(string orderID,string foodID,int purchaseCount,double priceOfOrder)
        {
            s_itemID++;
            ItemID = "ITID"+s_itemID;
            OrderID = orderID;
            FoodID = foodID;
            PurchaseCount = purchaseCount;
            PriceOfOrder = priceOfOrder;
        }
        /// <summary>
        /// Get the values from file read and assigned to specified property
        /// </summary>
        /// <param name="ItemData"></param>
        public ItemDetails(string itemData)
        {
            string[] values = itemData.Split(',');
            s_itemID = int.Parse(values[0].Remove(0,4));
            ItemID = values[0];
            OrderID = values[1];
            FoodID = values[2];
            PurchaseCount = int.Parse(values[3]);
            PriceOfOrder = int.Parse(values[4]);
        }

    }
}